version: "3.8"

services:
  tms-db:
    image: postgres:16.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      timeout: 15s
      interval: 10s
      retries: 5
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
        reservations:
          cpus: "0.2"
          memory: 300M

  tms-api:
    image: ultrashiptms:latest
    user: node
    command: pnpm start
    restart: always
    volumes:
      - ./:/usr/src/app
    depends_on:
      - tms-db
    ports:
      - '8080:8080'
    tty: true
    environment:
      POSTGRES_CONNECTION_URL: postgresql://tms_user:tms_pwd@tms-db:5432/ultraship_tms_db
      
volumes:
  db-data:
