version: "3.8"

services:
  tms-db:
    image: postgres:16.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      timeout: 15s
      interval: 10s
      retries: 5
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
        reservations:
          cpus: "0.2"
          memory: 300M

  tms-api:
    container_name: ultrashiptms-backend-container
    image: ultrashiptms-backend:latest
    depends_on:
      - tms-db
    environment:
      POSTGRES_CONNECTION_URL: postgresql://tms_user:tms_pwd@tms-db:5432/ultraship_tms_db
      JWT_SECRET: 'my-custom-secret'
      NODE_ENV: 'production'
      PORT: 8080
      X_REQUEST_HEADER: 'x-request-id-random'

  tms-frontend:
    container_name: ultrashiptms-frontend-container
    image: ultrashiptms-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always
    depends_on:
      - tms-api
      - tms-db

volumes:
  db-data:
