#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🛠️ Running build before push..."

# Run build
npm run build

# Check build result
if [ $? -ne 0 ]; then
  echo "❌ Build failed. Push aborted."
  exit 1
fi

echo "✅ Build passed. Proceeding with push."
